-- Table: public.Tarefas

-- DROP TABLE IF EXISTS public."Tarefas";

CREATE TABLE IF NOT EXISTS public."Tarefas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Titulo" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Descricao" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Prioridade" integer NOT NULL DEFAULT 1,
    "Status" integer NOT NULL DEFAULT 1,
    "DataDeCriacao" date NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Tarefas" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Tarefas"
    OWNER to postgres;